### PR TITLE
Add regression test for #1124

### LINKED ISSUE #1124: MRO failure on Python 3.7 with typing_extensions
### Steps to reproduce

Run the following script on Python 3.7:

```python
from astroid import parse
module = parse("""
import abc
import typing
import dataclasses

import typing_extensions

T = typing.TypeVar("T")

class MyProtocol(typing_extensions.Protocol): pass
class EarlyBase(typing.Generic[T], MyProtocol): pass
class Base(EarlyBase[T], abc.ABC): pass
class Final(Base[object]): pass
""")

#                    typing.Protocol
#                          |
# typing.Generic[T]    MyProtocol
#              \       /
#              EarlyBase     abc.ABC
#                       \    /
#                        Base
#                         |
#                        Final

final_def = module.body[-1]
final_def.mro()
```

### Current behavior

```
Traceback (most recent call last):
  File "xxx.py", line 31, in <module>
    print("mro:", final_def.mro())
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 3009, in mro
    return self._compute_mro(context=context)
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 2985, in _compute_mro
    mro = base._compute_mro(context=context)
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 2999, in _compute_mro
    return _c3_merge(unmerged_mro, self, context)
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 103, in _c3_merge
    context=context,
astroid.exceptions.InconsistentMroError: Cannot create a consistent method resolution order for MROs (tuple, object), (EarlyBase, tuple, Generic, object, MyProtocol), (ABC, object), (tuple, EarlyBase, ABC) of class <ClassDef.Base l.1347 at 0x7fa0efd52590>.
```

### Expected behavior

No MRO error is raised; Python 3.7 doesn't raise an error.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output

2.6.7-dev0; the test case fails in pylint 2.9.6 and on the main branch at commit 6e8699cef0888631bd827b096533fc6e894d2fb2.

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] Write a good description on what the PR does.

## Description

Closes #1124.

Regression test worked on my local machine with `3.7`. Hopefully CI passes as well.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

### CODE REVIEW

**Comment by DanielNoord** [comment]
Well, this took some tries to get right. But this passes and also checks the actual output of `mro()` to be correct 😄

**Comment by DanielNoord** [comment]
Ah this looks like it is running into a similar issue as https://github.com/PyCQA/pylint/pull/5697.

This is interesting. I'll investigate and see if I can find what is going wrong in both issues.

**Comment by DanielNoord** [comment]
@areveny Sorry for pinging you in this, but I saw you mention "spinning up a Windows machine". I have been stuck on this issue for the last couple of days. For some reason on Windows `3.10` the `mro()` or base classes for `typing_extensions.Protocol` don't match those of Linux and Mac...
I've gotten a friend of mine to send me `typing.py` and `typing_extensions.py` from her Windows installation but I couldn't spot any immediate differences..

If you can, I would really appreciate if you could take some minutes and see if you can find out what's going on here. 
For reference, we have the same issue in https://github.com/PyCQA/pylint/pull/5697 where an `import-error` is raised in Windows `3.10`...

**Comment by areveny** [comment]
I'll take a look at it. I use a Linux subsystem on Windows but I do have this machine handy to get it running and take a peek the best I can.

**Comment by areveny** [comment]
Okay, I can reproduce the bug consistently and locally. I haven't figured out the smallest first difference but here's the first difference:

In `_compute_mro` when `self=ClassDef.MyProtocol l10`, on Windows `inferred_bases=[]` because `Attribute.Protocol l10` is `uninferrable`. On Linux it can infer to `ClassDef.Protocol on line 1157` (of `typing.py`).

Also, the `typing.py` that is causing the error on Windows has different line numbers. I haven't checked out materially in detail how this file differs from the working one. I've uplodaded it below.
[typing.txt](https://github.com/PyCQA/astroid/files/7919618/typing.txt)

**Comment by areveny** [comment]
Recreation steps/ notes...

```
from astroid import parse
module = parse(
    """
import abc
import typing
import dataclasses

import typing_extensions

T = typing.TypeVar("T")

class MyProtocol(typing_extensions.Protocol): pass
class EarlyBase(typing.Generic[T], MyProtocol): pass
""")
```

Breakpoint in `node_ng.infer` line 164: `        for i, result in enumerate(generator):`.

Allow to recur three times until `self` is `Import l6`. Breakpoint at `ast_from_module_name` in `manager.py`.

Problem: This call `            found_spec = self.file_from_module_name(modname, context_file)` throws a caught `AstroidBuildingError` when importing `modname=typing_extensions`. So inference gets cut short or something.

**Comment by areveny** [comment]
Turns out `pip freeze` when doing `pip install -e astroid` on Windows is missing `typing_extensions==4.0.1`. Presumably it's like this in the cached Windows VM too. In fact it's different in a few ways from Linux.

Windows:
```
pip freeze
-e git+https://github.com/PyCQA/astroid.git@41b4a2991bbe0c42fd1d7a3acacf2acf41b49b43#egg=astroid
atomicwrites==1.4.0     
attrs==21.4.0
colorama==0.4.4
iniconfig==1.1.1        
lazy-object-proxy==1.7.1
packaging==21.3
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.7        
pytest==6.2.5
toml==0.10.2
wrapt==1.13.3
```

Solution: Manually install `typing-extensions` on Windows and the test passes. Not sure how we want to integrate this into our requirements files but this should do it!

**Comment by DanielNoord** [comment]
Ah I found the culprit. There is `typing-extensions>=3.10;python_version<"3.10"` in the `setup.cfg`. @Pierre-Sassoulas Do you know why there is a pin for `3.10`? I think we should install it either way, right?

**Comment by Pierre-Sassoulas** [comment]
Related MR:
Introduction: https://github.com/PyCQA/astroid/pull/986/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R42
Modification: https://github.com/PyCQA/astroid/pull/1157/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R43

Maybe the reason is that if typing_extension is not available in the version of python that we're already testing against even if it's in beta then the build is failing ?

**Comment by DanielNoord** [comment]
No the issue is (I think):
We don't need typing extensions on the latest supported python version. There is nothing typing extensions adds that is not already in 3.10. Therefore, the dependency is set up like that.
However, I assumed that typing extensions was a dependency and that therefore the tests would act similarly on all platforms and versions. I think typing extensions might be installed by default on Linux or something.

I think it makes sense that typing extensions is not a dependency so I'll update the tests to reflect that changed outcome on 3.10.

**Comment by Pierre-Sassoulas** [comment]
> We don't need typing extensions on the latest supported python version. There is nothing typing extensions adds that is not already in 3.10. Therefore, the dependency is set up like that.

Definitely. And we upgraded from < 3.8  to < 3.10 when we required things that were not in 3.9 or 3.8.

**Comment by DanielNoord** [comment]
Fixed!

**Review by Pierre-Sassoulas — APPROVED** [review]
Great !

**Pull request merged**
