### PR TITLE
Cut generator flags

### PR DESCRIPTION
**Pull request by nickdrozd**
This simplifies the code, and may slightly improve performance.

### CODE REVIEW

**Comment by PCManticore** [comment]
@nickdrozd Looks good! Can we get the CI green before merging?

**Comment by nickdrozd** [comment]
What's the current method for formatting?

**Comment by PCManticore** [comment]
We use `black` for that with `pre-commit` hooks, so the following should do it:

- install ``pre-commit`` using ``pip install pre-commit``
- then run ``pre-commit install`` in the ``astroid`` root directory to enable the git hooks.

**Comment by PCManticore** [comment]
@nickdrozd I merged this locally, thanks for the PR!

**Comment by nickdrozd** [comment]
Thanks! Btw, I've been out of the Python world for a while, but I'm back in it now, so hopefully I'll be contributing more.

**Pull request closed without merging**
