### PR TITLE
Fix finding packages without an ``__init__.py``

### LINKED ISSUE #1327: astroid 2.9.1 breaks pylint with missing __init__.py: F0010: error while code parsing: Unable to load file __init__.py
> Update 2022-01-04: Corrected repro steps and added more environment details

1. Set up simple repo with following structure (all files can be empty):
```
root_dir/
|--src/
|----project/ # Notice the missing __init__.py
|------file.py # It can be empty, but I added `import os` at the top
|----__init__.py
```
2. Open a command prompt
3. `cd root_dir`
4. `python -m venv venv`
5. `venv/Scripts/activate`
6. `pip install pylint astroid==2.9.1` # I also repro'd on the latest, 2.9.2
7. `pylint src/project` # Updated from `pylint src`
8. Observe failure:
```
src\project\__init__.py:1:0: F0010: error while code parsing: Unable to load file src\project\__init__.py:
```

### Current behavior
Fails with `src\project\__init__.py:1:0: F0010: error while code parsing: Unable to load file src\project\__init__.py:`

### Expected behavior
Does not fail with error.
> If you replace step 6 with `pip install pylint astroid==2.9.0`, you get no failure with an empty output - since no files have content

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.9.1

`python 3.9.1`
`pylint 2.12.2 `

This issue has been observed with astroid `2.9.1` and `2.9.2`

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Closes #1327 

Had no time to write tests yet, so if somebody can come up with something good: please take over this PR, you're more than welcome to.
Just wanted to illustrate that this is what should be added again.

This regression was introduced in 2ee20cc

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

@Pierre-Sassoulas, this might warrant a `2.9.3` release.

### CODE REVIEW

**Comment by interifter** [comment]
If you have a pointer to how to approach testing asteroid/pylint, in general, I might be able to help. It wouldn’t be too challenging to generate a temp directory that reproduces the problem.

Otherwise, I can write a test method the way I normally would that you can adapt?

**Comment by DanielNoord** [comment]
For some reason another test broke as well. I have got some spare time now, so I'll take a look myself. Thanks anyway 😄

**Comment by DanielNoord** [comment]
While I got the test suite to fail, I can't get the added test to fail without the change (thus it doesn't test anything..).

Would need to do some further investigation into what happened before the fauly commit in this function and what is happening now.

**Comment by Pierre-Sassoulas** [comment]
> If you have a pointer to how to approach testing asteroid/pylint, in general, I might be able to help. It wouldn’t be too challenging to generate a temp directory that reproduces the problem.

I think recreating a temp directory that reproduce the issue is the way to go here. Thank you for your help, much appreciated !

> Would need to do some further investigation

Could the problem come from the fact we removed the : ``os.path.expanduser(path))`` ? It's the first thing that comes to mind.

**Comment by DanielNoord** [comment]
Test now fails with previous code and passes with new code.

The mistake that we removed `pathname = _cache_normalize_path(pathname)`. Whereas `_canonicalize_path` also normalised the path, all paths that came from `path or []` where thus not normalised. This was problematic when path included `"."` and the normalised version of `"."` was not included in `sys.path`.
The tests also represent this scenario: we move into the tempdir and pass `"."` as `path`.

**Review by Pierre-Sassoulas — APPROVED** [review]
Let's release 2.9.3 with this.

**Pull request merged**
