### PR TITLE
AstroidManager: Expose ast_from_string method

### LINKED ISSUE #725: Create astroid module from a string using AstroidManager
For the read-from-stdin feature in pylint an AST is constructed using 

```py
AstroidBuilder(MANAGER).string_build(data, modname, filepath)
```
whereas for regular modules it is constructed using

```py
MANAGER.ast_from_file(filepath, modname, source=True)
```
See the get_ast method in https://github.com/PyCQA/pylint/pull/3257/files/5b24700e7bf84d1f2ae6fcd468acf5a9f6f1c458

The module docstring of astroid.manager suggests that the Manager should be used for both cases in pylint. 

Therefore, AstroidManager should provide a way to create an AST from a string.

### PR DESCRIPTION
**Pull request by anubh-v**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description
This PR exposes a new method `ast_from_string` in `AstroidManager`, which accepts source code as a string and returns the corresponding Astroid object. 

This method can be used directly instead of `AstroidBuilder.string_build`

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :hammer: Refactoring  |

## Related Issue

Fixes #725

### CODE REVIEW

**Comment by anubh-v** [comment]
Thanks for the feedback @PCManticore.
I'll update this shortly

**Comment by PCManticore** [comment]
@anubh-v Can you fix the formatting issues so we can merge this PR? 😄 Thank you for the contribution!

**Comment by anubh-v** [comment]
@PCManticore, I've fixed the error. Sorry for the delay

**Comment by anubh-v** [comment]
Thanks for reviewing this, and giving me a chance to contribute. Could I also get your feedback on my other PR at pylint [here](https://github.com/PyCQA/pylint/pull/3366) ? Thanks for your time

**Pull request merged**
