### PR TITLE
Find frozen stdlib modules

### LINKED ISSUE #1512: `collections_abc` will be frozen in 3.11
See https://docs.python.org/3.11/whatsnew/3.11.html#faster-startup

This includes the `_collections_abc` module which will break a lot of `pylint` tests. We don't generate a full `nodes.Module` for frozen modules so we don't know anything about the members of `collections`.

We should probably investigate this and find a way to overcome this.

### Current behavior

Fail to determine members of `collections` on `3.11`.

### Expected behavior

Determine members of `collections` on `3.11`.

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Closes #1512.

Related is https://github.com/python/cpython/issues/65935. I'm not sure how to test this on `3.10` though as this is a new feature on `3.11`. That would be the next step.
 
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

### CODE REVIEW

**Comment by DanielNoord** [comment]
Turns out this fixes all other outstanding issues with `3.11`. 😄 

I do wonder why the test suite is so incredibly slow though. Is that an issue with us? Or is `pytest` running slow on `3.11`?

**Comment by DanielNoord** [comment]
Locally, with `3.10`:
```console
2.10s call     tests/unittest_nodes.py::ImportNodeTest::test_from_self_resolve
1.34s call     tests/unittest_brain.py::SixBrainTest::test_attribute_access
1.25s call     tests/unittest_brain.py::ModuleExtenderTest::test_extension_modules
0.70s call     tests/unittest_manager.py::AstroidManagerTest::test_ast_from_class
0.61s call     tests/unittest_scoped_nodes.py::ClassNodeTest::test_mro_typing_extensions
0.55s call     tests/unittest_builder.py::BuilderTest::test_inspect_build0
0.46s call     tests/unittest_manager.py::AstroidManagerTest::test_ast_from_class_with_module
0.42s call     tests/unittest_builder.py::BuilderTest::test_inspect_build_type_object
0.38s call     tests/unittest_brain.py::CollectionsDequeTests::test_deque
0.31s call     tests/unittest_brain.py::ReBrainTest::test_re_pattern_subscriptable
0.29s call     tests/unittest_inference.py::InferenceTest::test_unary_operands
0.29s call     tests/unittest_scoped_nodes.py::ModuleNodeTest::test_stream_api
0.28s call     tests/unittest_scoped_nodes.py::ClassNodeTest::test_has_dynamic_getattr
0.26s call     tests/unittest_brain.py::DateutilBrainTest::test_parser
0.24s call     tests/unittest_brain.py::TypingBrain::test_callable_type
0.24s call     tests/unittest_nodes.py::ImportNodeTest::test_bad_import_inference
0.24s call     tests/unittest_brain.py::MultiprocessingBrainTest::test_multiprocessing_manager
0.23s call     tests/unittest_brain.py::AttrsTest::test_attr_transform
0.21s call     tests/unittest_builder.py::test_module_build_dunder_file
0.19s call     tests/unittest_brain.py::SubprocessTest::test_popen_does_not_have_class_getitem
```

With `3.11.0a7`:
```console
1.83s call     tests/unittest_nodes.py::ImportNodeTest::test_from_self_resolve
1.33s call     tests/unittest_brain.py::ModuleExtenderTest::test_extension_modules
0.67s call     tests/unittest_brain.py::test_http_client_brain
0.59s call     tests/unittest_scoped_nodes.py::ClassNodeTest::test_mro_typing_extensions
0.58s call     tests/unittest_builder.py::BuilderTest::test_inspect_build_type_object
0.55s call     tests/unittest_manager.py::AstroidManagerTest::test_ast_from_class_with_module
0.47s call     tests/unittest_builder.py::BuilderTest::test_inspect_build0
0.34s call     tests/unittest_manager.py::AstroidManagerTest::test_ast_from_class
0.33s call     tests/unittest_brain.py::CollectionsDequeTests::test_deque
0.32s call     tests/unittest_scoped_nodes.py::ModuleNodeTest::test_without_docstring
0.32s call     tests/unittest_brain.py::TypingBrain::test_callable_type
0.29s call     tests/unittest_brain.py::AttrsTest::test_attr_transform
0.25s call     tests/unittest_brain.py::ReBrainTest::test_regex_flags
0.23s call     tests/unittest_scoped_nodes.py::ClassNodeTest::test_has_dynamic_getattr
0.21s call     tests/unittest_brain.py::MultiprocessingBrainTest::test_multiprocessing_manager
0.21s call     tests/unittest_inference.py::InferenceTest::test_no_infinite_ancestor_loop
0.19s call     tests/unittest_nodes.py::ImportNodeTest::test_bad_import_inference
0.17s call     tests/unittest_brain.py::ReBrainTest::test_re_pattern_subscriptable
0.17s call     tests/unittest_builder.py::test_module_build_dunder_file
0.16s call     tests/unittest_inference.py::InferenceTest::test_two_parents_from_same_module
```

So, possible something to do with the runner/GA?

**Comment by DanielNoord** [comment]
I got some data in https://github.com/DanielNoord/astroid/pull/20.

Not immediately sure what is causing this. But since `main` is also affected I don't think it is due to this PR.

**Review by cdce8p — APPROVED** [review]
LGTM! A very elegant solution. Thank you @DanielNoord 🐬

**Comment by cdce8p** [comment]
> I do wonder why the test suite is so incredibly slow though. Is that an issue with us? Or is `pytest` running slow on `3.11`?

One part was the cache which didn't got stored until you fixed all the issues. That's already (1:30min).
The other one, I would guess, is that Python 3.11 isn't installed natively and thus probably not optimized. Just compare the `Setup Python` steps:
* [3.10 run](https://github.com/PyCQA/astroid/runs/6135500126?check_suite_focus=true#step:3:1)
* [3.11 run](https://github.com/PyCQA/astroid/runs/6135499750?check_suite_focus=true#step:3:1)

**Comment by DanielNoord** [comment]
@cdce8p DanielNoord#20 shows significant in test times though. `numpy` brain tests seem to struggle but other test also run twice as long. That shouldn't be due to caching nor installing python right?

**Comment by cdce8p** [comment]
> @cdce8p [DanielNoord#20](https://github.com/DanielNoord/astroid/pull/20) shows significant differences in test times though. `numpy` brain tests seem to struggle but other test also run twice as long. That shouldn't be due to caching nor installing python right?

It could be 🤷🏻‍♂️ Caching not so much, but optimizations during install are a possibility. Especially if that time difference doesn't happen locally. I only noticed the different log output.

**Pull request merged**
