### PR TITLE
Use pylint-config minimal option to move pylint config into pyproject.toml

### PR DESCRIPTION
**Pull request by cclauss**
## Steps

- [ ] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description
```
pipx install git+https://github.com/PyCQA/pylint.git
pylint-config --rcfile=pylintrc generate --interactive .
* Do you want a minimal configuration without comments or default values?
    (y)es or (n)o  (default=no) y
git rm pylintrc
```
Sorting longer arrays like plugins and disable makes duplicates jump out like `pylint.extensions.code_style`
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
@cclauss this branch was the one we should keep, right ? I think we can remove old values that are not the default and it's good to go (thank you!)

**Comment by DanielNoord** [comment]
I self requested a review because there were some comments that shouldn't be removed, for example a `TODO` that can probably actually be fixed.
I don't think `pylint-config` will ever be able to notice this so we will still need to validate if there aren't any useful comments in the old file.

**Comment by cclauss** [comment]
I think that this process should be a way to test PyCQA/pylint#7484 as well as the new pylint-config minimal approach.  If we merge a PR that has a lot of manual modifications then that testing opportunity is gone.  I will leave it to pylint experts to complete this process.

**Comment by Pierre-Sassoulas** [comment]
Some values are not the default, but we need to remove them anyway because the default is good enough (astroid did not need the "CVS" option for more than 10+ years for example).

**Pull request closed without merging**
