### PR TITLE
Fix unpack_infer() to fail if results are empty.

### PR DESCRIPTION
**Pull request by dbaum**
As expected, this will also fix pylint so that it correctly deals with "raise ()" in the python3 checker.

### CODE REVIEW

**Comment by PCManticore** [comment]
Merged localy https://github.com/PyCQA/astroid/commit/99a3870d4ba212a036dd629ad9ee020333009425. I also squashed your commits into one and cherry-picked it in multiple branches.

**Comment by dbaum** [comment]
Thanks!

I'm new to using github, etc.  Is there something I should have done to
make the pull easier for you?  Should I have combined the commits
together?  Should I have not tried to synced with upstream/master?

I'm asking because it is likely that I'll have a few more small patches to
astroid in the near future and I want to make things as smooth as possible
for you.

Dave

**Comment by PCManticore** [comment]
No worries. I prefer to have the commits squashed if they are not part of a bigger feature, in that case having some smaller chunks makes more sense. Also you should use rebase for feature branches, so that you won't be needing syncing with the upstream/master. It should be good after that, the cherry-picking is something that I must do, since we have multiple branches of development at the moment.

Thanks for the (future) contributions, let me know if there is something I could help you with.

**Comment by dbaum** [comment]
I'm trying to understand the workflow.  Should I be doing my work on a
brach, keep my master at (or behind) the upstream master, then rebase my
feature branch to master and squash the commits at that point?  Something
like:

git checkout -b new-feature master
git commit -a -m "some work"
git commit -a -m "some more work"

# I'm a little fuzzy on exactly what commands to use here.  The idea is to
bring my
# master up to date with the upstream master.
git pull upsstream/master

# Go back to working on my fix...
git checkout new-feature
git commit -a -m "even more work"

# Clean things up before a pull request.
git rebase -i master

**Comment by PCManticore** [comment]
Exactly, that's the workflow that I'm using mostly.

**Pull request closed without merging**
