### PR TITLE
Allow lazy-object-proxy >= 1.5.0

### LINKED ISSUE #800: lazy-object-proxy update to 1.5.0 breaks astroid
### Steps to reproduce
1. locally install lazy-object-proxy==1.5.0
2. locally install astroid

### Current behavior
Exception
> Requirement.parse('lazy_object_proxy==1.4.*'), {'astroid'})

### Expected behavior
Works as before, as I don't see any breaking changes in lazy-object-proxy
Before e1b4e11e383bf281544f1300e41eea2ac6ab251c this would have worked

### PR DESCRIPTION
**Pull request by priv-kweihmann**
by allowing every version >= 1.4.0

Fixes #800

## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Allow lazy-object-proxy version >= 1.5.0

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|    | :sparkles: New feature |
|    | :hammer: Refactoring  |
|    | :scroll: Docs |

## Related Issue

Closes #800

### CODE REVIEW

**Comment by ViktorHaag** [comment]
If the purpose of the original pinning was to lower the risk of breaking changes in a dependency, would it not be better for this PR to pin to versions <2 for the dependency than admit for future, potentially breaking, versions?

**Comment by priv-kweihmann** [comment]
Don't know, never heard anything back about the original reasoning of the version pinning.
And to be honest a breaking API change could happen with any version update (as nobody seems to care really about a proper versioning scheme) - so I personally think that setting a base version and accepting any version higher than that, is the way it should be done - as fixes for newer versions have to be done anyway (if not now than at some point in the future)

**Comment by priv-kweihmann** [comment]
Any news of this item? Can I do something to get this merged?

**Comment by stonebig** [comment]
I would hope if you change it to "lazy_object_proxy>=1.4,<1.6" it may be accepted

**Comment by FelixMoelder** [comment]
A merge would be nice, as `lazy-object-proxy 1.4.x` is not available on conda-forge for osx-arm64.

**Comment by efwahl** [comment]
The ==1.4.* pinning is breaking with other packages which have an explicit 1.5 requirement and the new pip resolver behavior. It would be nice to have a fix promptly.

**Comment by AadamZ5** [comment]
I'm also running into issues with the `==1.4.*` pinning having conflicts with other packages in my project. It seems like this PR would be fine to move in with `>=1.50`. The sooner the better 😊, and thank you for your help!

**Comment by PCManticore** [comment]
Thanks for the PR.

**Pull request merged**
