### PR TITLE
Demonstrate a problem with attrs w/ annotations

### PR DESCRIPTION
**Pull request by webknjaz**
## Steps

- [ ] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

This PR extends attrs tests in order to demonstrate a not-yet-covered case.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug demo  |

## Related Issue

N/A

### CODE REVIEW

**Comment by PCManticore** [comment]
Hey @webknjaz Thanks for the PR. I'm not entirely sure what's the problem exactly? Can you open an issue instead?

**Comment by webknjaz** [comment]
Yes sure. Looks like it's the issue already exists: https://github.com/PyCQA/astroid/issues/724.

**Comment by webknjaz** [comment]
@belm0 is this what you asked in #724?

**Comment by belm0** [comment]
I mentioned later in the original issue, but this is foremost a deficiency of type-annotated attributes on plain classes (not using attrs library). 

https://github.com/PyCQA/astroid/issues/724#issuecomment-555473451

I gave example code there ("`obj.o2.foo2()`" should yield a pylint warning).

**Comment by webknjaz** [comment]
Oh, so *almost* the same but not quite.

**Pull request closed without merging**
