### PR TITLE
Bug pylint 4896

### PR DESCRIPTION
**Pull request by hippo91**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description
This PR adds a brain module to allow the inference of the `value` attribute of `ctypes` redefined types.
In a first try, i tried to implement a method based on an inference tip that was focused on the inference of the `value` attribute.
While the inference was correct, i have been unable to build a predicate that targeted precisely the `value` attribute of `c_types` instances. Thus the inference tip was also applied for too many classes and leads to inference problem (infinite recursions) in the unittest dedicated to the `enum` brain.
Instead this PR proposes an extension of the `ctypes` modules in which every `ctypes` redefined types is overloaded with its two members (`value` and `_type_`) redefined.
 

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue
Closes PyCQA/pylint#4896

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM :)

**Review by cdce8p — APPROVED** [review]

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Do you want to release it with `2.7.3` or do `2.8.0` next?

**Comment by Pierre-Sassoulas** [comment]
I don't think there were major changes so I was going to uput everything in 2.7.3, but I don't have strong opinion about that.  I can put all the new change in 2.7.3 or in 2.8.0. What do you suggest ?

**Comment by cdce8p** [comment]
The majority of changes would probably qualify as bugfix, so `2.7.3` should be fine. Just wanted to ask after I saw changelog entries for both `2.7.3` and `2.8.0`.

**Pull request merged**
