### PR TITLE
object.__new__(cls) calls fails to infer correct type when used in inherited classmethod

### PR DESCRIPTION
**Pull request by rogalski**
These tests are MCVE that exposes root cause of PyCQA/pylint#224

TODO
- [x] implement tests
- [ ] implement fixes
- [ ] add changelog entries

### CODE REVIEW

**Comment by PCManticore** [comment]
@rogalski Need any help over here?

**Comment by brycepg** [comment]
It's interesting that `return cls()` and `return object.__new__(D)` both work properly

**Comment by brycepg** [comment]
Well, I've found the source of the issue right [here](https://github.com/PyCQA/astroid/blob/master/astroid/bases.py#L310). The problem is I'm not sure how to fix it because of another bug.

`astroid` currently has a UnboundMethod to instantiate object.__new__ calls. The problem is that the `context.boundnode` is now pointing to `object`. `cls` gets inferred to the wrong class because no context is given upon inference (and if you add the context it will point to object)

**Comment by PCManticore** [comment]
It sounds to me that we'd need to provide a correct `boundnode` when inferring a `Call` node (https://github.com/PyCQA/astroid/blob/b604b267f4876298d142f165713d6be1bd77790e/astroid/inference.py#L189), paired with passing a context to the `infer_call_result` in the `UnboundMethod.infer_call_result` method.

**Comment by brycepg** [comment]
@PCManticore so for `UnboundMethod` calls the `boundnode` should be the type of the first argument?

**Comment by brycepg** [comment]
I think this may be related to #177

**Pull request closed without merging**
