### PR TITLE
Stop detecting modules compiled by `cffi` as namespace packages

### LINKED ISSUE #1776: Issue linting CFFI modules
### Steps to reproduce

1. Install the following in the user site-packages
```
pip install -q --user pylint
pip install -q --user git+https://github.com/wolever/python-cffi-example.git
```

2. Run the following snipped in a terminal (tested on Fedora 36 with system Python 3.10)
```
cd /tmp
cat <<EOF > .pylintrc
[MASTER]
extension-pkg-whitelist = cffi_example._person
EOF

cat <<EOF > test.py
from cffi_example._person import ffi, lib
EOF

pylint test.py
```

### Current behavior
```
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
cffi_example._person.lib
Exception on node <ImportFrom l.1 at 0x7f637397f700> in file '/tmp/test.py'
Traceback (most recent call last):
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/modutils.py", line 590, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, [context])
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 393, in find_spec
    finder, spec = _find_spec_with_path(
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 362, in _find_spec_with_path
    raise ImportError(f"No module named {'.'.join(module_parts)}")
ImportError: No module named cffi_example._person.lib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dalcinl/.local/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/home/dalcinl/.local/lib/python3.10/site-packages/pylint/checkers/imports.py", line 523, in visit_importfrom
    self._add_imported_module(node, f"{imported_module.name}.{name}")
  File "/home/dalcinl/.local/lib/python3.10/site-packages/pylint/checkers/imports.py", line 833, in _add_imported_module
    importedmodname = astroid.modutils.get_module_part(
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/modutils.py", line 438, in get_module_part
    file_from_modpath(
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/modutils.py", line 334, in file_from_modpath
    return file_info_from_modpath(modpath, path, context_file).location
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/modutils.py", line 384, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/modutils.py", line 593, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 393, in find_spec
    finder, spec = _find_spec_with_path(
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 355, in _find_spec_with_path
    spec = finder_instance.find_module(
  File "/home/dalcinl/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 205, in find_module
    submodule_path = sys.modules[modname].__path__
AttributeError: cffi library 'cffi_example._person' has no function, constant or global variable named '__path__'
test.py:1:0: F0002: test.py: Fatal error while checking 'test.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/dalcinl/.cache/pylint/pylint-crash-2022-09-09-21-23-07.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)

```

### Expected behavior

No traceback!

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
```
2.12.9
```

### Additional information
CFFI inject objects in `sys.modules` that are not real module objects:
```
In [1]: import sys

In [2]: import cffi_example._person

In [3]: lib = sys.modules['cffi_example._person.lib']

In [4]: print(type(lib), type(lib).__base__)
<class '_cffi_backend.Lib'> <class 'object'>

In [5]: lib
Out[5]: <Lib object for 'cffi_example._person'>
```
As `astroid` is asking for the missing `__path__` attribute, things go bad.
However, looking at `astroid` sources, I don't think that the root of the issue, but rather a confusion with detection of namespace packages.

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

The `is_namespace()` changes in 2.12 broke introspection of modules compiled by `cffi`, which as quoted in the issue, patch `sys.modules`. The only reason we are looking at `sys.modules` is to support the edge case of old `pkg_resources`-style namespace packages. The principle of false negatives are better than letting things crash suggests that we should just loosen the check to top level modnames ("pylint" rather than "pylint.lint"), because that allows the `cffi` modules to not crash without failing the `pkg_resources` tests. (Another way of saying: I'm not aware of any false negatives we're causing with `pkg_resources`-style packages, since the tests pass, but I can't rule it out.)

No tests--did not want to introduce a test dependency on `cffi`.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

Closes #1776
Closes PyCQA/pylint#7399

@dalcinl, does this resolve your issue?

### CODE REVIEW

**Comment by dalcinl** [comment]
> @dalcinl, does this resolve your issue?

I'm having trouble to reproduce using my usual workflow. 
Something fishy is going on with installation:
```
$ git clone -b cffi https://github.com/jacobtylerwalls/astroid
Cloning into 'astroid'...
remote: Enumerating objects: 28602, done.
remote: Counting objects: 100% (339/339), done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 28602 (delta 229), reused 229 (delta 166), pack-reused 28263
Receiving objects: 100% (28602/28602), 16.02 MiB | 11.88 MiB/s, done.
Resolving deltas: 100% (17660/17660), done.

$ cd astroid/

$ pip install -U .
Defaulting to user installation because normal site-packages is not writeable
Processing /tmp/astroid
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=14192 sha256=fbeb6557180aaaf819a561e9dff4abd88a0f0b5f705145c133fceee03aadc793
  Stored in directory: /tmp/pip-ephem-wheel-cache-z9qsa0dx/wheels/f0/82/7c/de80ba3afb992294acfa1eb14309533e9df9441d37974f9de1
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
```

Note that this happens when trying to install to the user site-packages. Virtualenv installations seems to be OK.
The following invocation should work as a quick reproducer to avoid messing with the default user site.
```
PYTHONUSERBASE=/tmp/user python -m pip install .
```

**Comment by Pierre-Sassoulas** [comment]
Could you try installing in a virtualenv with ``pip install pylint -U`` then ``pip install -U git+https://github.com/jacobtylerwalls/astroid@cffi``, please ?

**Comment by dalcinl** [comment]
@Pierre-Sassoulas I think I've not been clear enough. Within a virtualenv (`python -m venv`), everything works OK. Even the last release of `astroid` is OK, no issue at all. If I install `astroid` from your cffi branch, it also work, not problem at all.

All the trouble happens when trying to install in the user site-packages directory:
1) pylint raises exception if using `astroid` last release (the issue this PR is addressing)
2) I cannot `pip install -U git+https://github.com/jacobtylerwalls/astroid@cffi` to test your branch.

**Comment by Pierre-Sassoulas** [comment]
> All the trouble happens when trying to install in the user site-packages directory:

I don't know if I understood correctly what user site package is but wouldn't ``pip install -U git+https://github.com/jacobtylerwalls/astroid@cffi --user`` works then ?

**Comment by dalcinl** [comment]
> I don't know if I understood correctly what user site package is but wouldn't `pip install -U git+https://github.com/jacobtylerwalls/astroid@cffi --user` works then ?

No! That's exactly what is broken (in recent pip releases, the `--user` flag is implicit if the user does not have permissions to install in the system site-packages):

```
$ pip install -U git+https://github.com/jacobtylerwalls/astroid@cffi --user
Collecting git+https://github.com/jacobtylerwalls/astroid@cffi
  Cloning https://github.com/jacobtylerwalls/astroid (to revision cffi) to /tmp/pip-req-build-sq86tbq0
  Running command git clone --filter=blob:none --quiet https://github.com/jacobtylerwalls/astroid /tmp/pip-req-build-sq86tbq0
  Running command git checkout -b cffi --track origin/cffi
  Switched to a new branch 'cffi'
  branch 'cffi' set up to track 'origin/cffi'.
  Resolved https://github.com/jacobtylerwalls/astroid to commit 108f675190b57bda9c67ae6c9dbfadf6b3fa2236
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=14192 sha256=2ab4f866e79db6988aa41d1ac39c7ea51f257b903cdd24180031697f5bbf2472
  Stored in directory: /tmp/pip-ephem-wheel-cache-_xn105fv/wheels/ab/08/1c/bc59387b93efa124d6c0ac7fdebb60a524ad44a805035d026d
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```
Note the `UNKNOWN-0.0.0` package name and version!

I install stuff in the user site-packages directory (`--user` flag) all the time. This is the first time ever I see such failure. Maybe it is a pip/setuptools issue, but as I said, this is the first time ever I see this happening.

**Comment by dalcinl** [comment]
OK, this is what I did to manually try this PR

1. Clone your git repo at the `cffi` branch.
2. `python -m build --wheel`
3. `pip install dist/astroid-2.13.0.dev0-py3-none-any.whl`

After that, I ran `pylint` on my `cffi`-based project, and the issue is resolved. 
Therefore, from my side, this PR is good to merge. Thank you for the quick fix!

However, the issue of installing with pip from a git repo is still there. My git clone is in "/tmp/astroid":
```
$ cd /tmp/astroid
$ pip install . --user
Processing /tmp/astroid
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=14192 sha256=960182c3b0f0ce5a4f50e2c58a20166c474365f4765533a49b9987c856fd0a6f
  Stored in directory: /tmp/pip-ephem-wheel-cache-1gupxqry/wheels/f0/82/7c/de80ba3afb992294acfa1eb14309533e9df9441d37974f9de1
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```
BTW, this issue occurs with the `main` branch also, so this is definitely not a regression from your fixes for `cffi`.

**Comment by Pierre-Sassoulas** [comment]
OK, thank you for walking me through it. We switched to ``pyproject.toml`` in https://github.com/PyCQA/astroid/pull/1670 this is probably the reason why it fail. What is your version of setuptools ?

**Comment by rjarry** [comment]
This commit fixes https://github.com/PyCQA/pylint/issues/7399

Thanks!

**Comment by dalcinl** [comment]
@rjarry I'm using latest pip and setuptools (both installed in the user site-packages directory) with Fedora 36 system Python 3.10.6.
```
$ python -m pip list --user | egrep "pip|setuptools"
pip                           22.2.2
setuptools                    65.3.0
```

**Comment by rjarry** [comment]
@dalcinl I do not install with `--user`. I am using a virtual env. Here are the package versions with which it works:

```
astroid @ git+https://github.com/jacobtylerwalls/astroid@108f675190b57bda9c67ae6c9dbfadf6b3fa2236
dill==0.3.5.1
isort==5.10.1
lazy-object-proxy==1.7.1
mccabe==0.7.0
platformdirs==2.5.2
pylint==2.15.2
tomli==2.0.1
tomlkit==0.11.4
wrapt==1.14.1
```

**Comment by dalcinl** [comment]
@rjarry Yes, I know, virtual envs are working fine. It is with the `--user` flag that things go wrong. Did you try? You can reproduce the issue the following way (to not alter your default user site-packages) by setting the `PYTHONUSERSITE` environment variable.
```
PYTHONUSERSITE=/tmp/user python -m pip install git+https://github.com/jacobtylerwalls/astroid@108f675190b57bda9c67ae6c9dbfadf6b3fa2236
```

**Comment by DanielNoord** [comment]
@jacobtylerwalls Do you know if `cffi` is also affected by https://github.com/PyCQA/astroid/pull/1752?

**Comment by jacobtylerwalls** [comment]
> Do you know if cffi is also affected by https://github.com/PyCQA/astroid/pull/1752?

I don't, sorry.

#1752 won't be backported, so what do you think about going ahead and getting this bugfix out?

**Comment by DanielNoord** [comment]
> > Do you know if cffi is also affected by #1752?
> 
> I don't, sorry.
> 
> #1752 won't be backported, so what do you think about going ahead and getting this bugfix out?

I'll have a look if this is fixed by it. If so, this will probably become uncovered on `2.13` so we might want to add a `TODO` about it.
Changes itself look fine though so I'll merge after my investigation!

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you @jacobtylerwalls ! Let's release astroid 2.12.10 and pylint 2.15.3 once this is merged :)

**Review by DanielNoord — APPROVED** [review]
This is not affected by custom import hooks as fixed in https://github.com/PyCQA/astroid/pull/1752.

**Comment by jacobtylerwalls** [comment]
Thanks for investigating, I appreciate it!

**Pull request merged**
