### PR TITLE
Cut cache_generator

### PR DESCRIPTION
**Pull request by nickdrozd**
Is cache_generator doing anything? Cutting it doesn't break anything
as far as I can tell, and it Pylint even seems to go a little faster
without it.

### CODE REVIEW

**Comment by nickdrozd** [comment]
Someone else should try this on a large repo and see what happens.

**Comment by PCManticore** [comment]
It's possible `cache_generator` is not having the performance impact we expected it to have, but having some tests with `pylint` on top of libraries like `numpy` or `pandas` could prove that.

**Comment by kodonnell** [comment]
As per [here](https://github.com/PyCQA/astroid/issues/529#issue-310116375): 

> Allow partial caching. Currently an inference value is only cached if the inference is completely exhausted. Since there are many instances of only retrieving the first value of the inference, caching is ignored because there is no partial caching.

So - probably want to fix it (easy?) as opposed to getting rid of it - and hopefully that'll actually improve performance.

**Comment by PCManticore** [comment]
Yeah, that makes sense, it is possible that addressing some of its flaws could result in a performance improvement albeit minor.

**Pull request closed without merging**
