### PR TITLE
Move NodeNG to its own file

### PR DESCRIPTION
**Pull request by brycepg**
NodeNG is getting really big. Time to refactor node_classes.py

If this is accepted, then I will continue to split up `node_classes.py` for #465

### CODE REVIEW

**Comment by PCManticore** [comment]
After seeing what this refactoring would entail, I honestly think this kind of refactoring is going to generate an unreasonable amount of churn, especially resulting in more confusing git blames. I'm not entirely sure this is actually worth doing it. Is that file even that big, considering that a big chunk of its size are the actual docstrings? If I recall, it was around 2000 or so lines, which is kind of big, but not necessarily unmanageable. There's also the question on what exactly would be break out after we get `NodeNG` to its own file. Would we move every node into its own file? That's going to become unmanageable as well, since now we'd have to jump to one of the 30-40 new files in order to look up a node, instead of looking it up in a single place. I don't think this makes sense, as it feels a bit a refactoring for the refactoring's sake.

**Comment by brycepg** [comment]
possible pros to refactoring node_classes.py:

* Easier keep track of what method belongs to what class
* Related classes could be logically grouped together (List, Tuple, Set, go in `container_nodes.py` or `nodes/containers.py`)

**Comment by Pierre-Sassoulas** [comment]
I'm convinced by @brycepg argument, the node_classes and scope_nodes are unmanageable right now and in particular fixing the circular import is a nightmare without a clear understanding of what needs what and literally hundreds of import per file.

**Comment by Pierre-Sassoulas** [comment]
Closing because I did not realize it was a MR and not an issue. Rebasing would cost much more than just redoing it.

**Pull request closed without merging**
