### PR TITLE
Ensure NodeNG.get_children yield nodes in source code order

### PR DESCRIPTION
**Pull request by brendanator**
### Fixes
- In Arguments, an argument, its annotation and its default are yielded before the next argument
- In IfExp, the body nodes is yielded before the test node

Fixes the ordering issue from #585

### CODE REVIEW

**Comment by nickdrozd** [comment]
I have no objection to changing the order in `IfExp.get_children`, but
the change in `Arguments.get_children` looks suspicious to me. In
general, `get_children` implementations are not elegantly written, but
that's because the function is a hotspot and the loops have been
unrolled in the name of speed. Adding the complexity of `_yield_args`
could slow things down, and we need to be careful to avoid that.

But how about this for a compromise? Add a new function
`get_children_in_order`. In most cases, this would just be
`get_children`:

```
class NodeNG:
	def get_children(self):
		'''Yield children in unspecified order'''
		# ...

	def get_children_in_order(self):
		'''Yield children in order they appear in the code'''
		# in most cases the children already appear in order
		yield from self.get_children()


class Return(NodeNG):
	def get_children(self):
		if self.value is not None:
			yield self.value

	# inherits get_children_in_order from NodeNG
```

But with `Arguments`, the implementation would be more particular:
```
class Arguments(NodeNG):
	def get_children(self):
		# as it is now

	def get_children_in_order(self):
		# new implementation with _yield_args
```

This way, we don't need to mess with the spec for `get_children`, and
implementations of `get_children_in_order` can be altered without
concern for general slowdown.

**Comment by brendanator** [comment]
You are right @nickdrozd 

I profiled it and there is definitely some overhead from `_yield_args`. I tried 3 versions
* Original - baseline
* `_yield_args` version (the current PR) - 2.88 times as long to execute `get_children`
* Inline the yield args calls - 1.71 times as long to execute `get_children`

I'm happy to inline the calls if that's what's wanted.

It seems like adding a new function `get_children_in_order` would clutter the API a bit needlessly to avoid a smallish slowdown in a single node class, after all I could just monkey patch it to get the functionality I need.

I can do whichever though so let me know

**Comment by PCManticore** [comment]
I agree with @nickdrozd on this one. astroid and pylint are so slow that performance should trump most of the other initiatives, as long as those initiatives are not related to furthering the capabilities of astroid itself (e.g. inference or control flow). 
The question now is why it's so important to have the iteration done in the order of the definition. Do you have a particular case that the current behaviour is impeding or it's more of an irk? I feel that a `get_children_in_order` could make sense but I'm not sure if it's so worth having without an use case.

**Comment by brendanator** [comment]
OK, doesn't seem like it's worth it then

**Pull request closed without merging**
