### PR TITLE
Revert "Revert "Remove useless NoReturn in NodeNG.statement's typing (#1304)""

### PR DESCRIPTION
**Pull request by tushar-deepsource**
Reverts PyCQA/astroid#1307

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Blocked by #1316

**Review by Pierre-Sassoulas — APPROVED** [review]
Thanks for getting to the bottom of the issue !

**Comment by Pierre-Sassoulas** [comment]
Nvm, as @cdce8p said, we can merge before fixing #1316 when we see that the fail are unrelated to the changes.

**Comment by cdce8p** [comment]
Thanks @tushar-deepsource!

**Pull request merged**
