### PR TITLE
Add typing to ``_normalize_path`` and ``_cache_normalize_path``

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] Write a good description on what the PR does.

## Description

Small fix that adds typing to `_NORM_PATH_CACHE` and related methods.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
This will cause conflict in #1253, which was not merged yet because... I don't know why.

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I think it should be rebased on top of #1253 once it's merged.

**Comment by DanielNoord** [comment]
This became a very small change 😄

**Review by Pierre-Sassoulas — APPROVED** [review]
:smile: I admit I've seen you fixing more typing error at once than that before !

**Pull request merged**
