### PR TITLE
Bug pylint 2594

### PR DESCRIPTION
**Pull request by hippo91**
## Description
This PR fixes the PyCQA/pylint#2594. 
The problem arises in the `BaseInstance` class of the `astroid.bases` module in the method `_wrap_attr` at line 248. The test
```
if attr.statement().scope() == self._proxied:
```
failed, preventing the return of a `BoundMethod` instance.

Despite the fact that i'm uncomfortable with this, I deleted this test and all unit tests are ok. 
I added a unittest which makes sure that a method wich is a lambda built from a function is well infered as a `BoundMethod`.  

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

## Related Issue

Closes PyCQA/pylint#2594

### CODE REVIEW

**Comment by PCManticore** [comment]
Hey @hippo91 Sorry for the late review. This look okay to me but can you check this PR against `pylint`? It might be that that line was added to fi a pylint bug, but no tests were added to astroid itself.

**Comment by hippo91** [comment]
@PCManticore i used `pylint` over itself with the `master` branch of `astroid` and the `bug_pylint_2594` branch and both of them gave me same results:
```
************* Module pylint.extensions.mccabe
pylint/extensions/mccabe.py:23:8: E1123: Unexpected keyword argument 'name' in method call (unexpected-keyword-arg)
pylint/extensions/mccabe.py:23:8: E1123: Unexpected keyword argument 'entity' in method call (unexpected-keyword-arg)
pylint/extensions/mccabe.py:23:8: E1123: Unexpected keyword argument 'lineno' in method call (unexpected-keyword-arg)
pylint/extensions/mccabe.py:23:8: E1120: No value for argument 'node' in method call (no-value-for-parameter)
************* Module pylint.checkers.raw_metrics
pylint/checkers/raw_metrics.py:19:0: W0611: Unused Any imported from typing (unused-import)
************* Module pylint.checkers.imports
pylint/checkers/imports.py:41:0: C0411: third party import "import isort" should be placed before "import astroid" (wrong-import-order)
************* Module pylint.checkers.python3
pylint/checkers/python3.py:33:0: W0611: Unused FrozenSet imported from typing (unused-import)
************* Module pylint.checkers.base
pylint/checkers/base.py:45:0: W0611: Unused Pattern imported from typing (unused-import)

------------------------------------------------------------------
Your code has been rated at 9.98/10 (previous run: 9.98/10, +0.00)
```
Is this what you meant by `check this PR against pylint`?

**Comment by hippo91** [comment]
@PCManticore do you want me to merge into the trunk?

**Comment by PCManticore** [comment]
@hippo91 Yes, definitely!

**Pull request merged**
