### PR TITLE
Add typing to ``__str__``, ``__repr__`` and ``_repr_name``

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] Write a good description on what the PR does.

## Description

Puts `mypy astroid` under 90 errors.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Related Issue

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
90 errors only ? Is the goal of fully typed astroid for 2.10 is reachable according to you ?

**Comment by DanielNoord** [comment]
> 90 errors only ? Is the goal of fully typed astroid for 2.10 is reachable according to you ?

No! These are just the errors you get when trying to run `mypy` without any arguments. `mypy --strict` returns 2437 errors.
If we solve these 90 we can turn `mypy` on in `pre-commit` though, which should help!
However, I'd be surprised if we would get these 90 fixed in `2.11` honestly. There are some pretty big issues still open, most of which have to do with non-optional attributes being typed as optional.

**Comment by Pierre-Sassoulas** [comment]
> mypy --strict returns 2437 errors.

Approximately the same than for pylint :smile:  I hope that doing astroid first will make pylint easier though. 

It will help to be able to activate mypy if only so we don't introduce knew problem unknowingly. Maybe we should add type ignores on existing issues so we can activate mypy right now anyway ? With less than a hundred error left it seems feasible.

**Comment by DanielNoord** [comment]
I don't think we should do that. We would ignore important issues that might require refactoring. If we then start increasing typing build on incorrect code we can create problems for our future selves.

To give a rough summary I think of the 90 error still open:
20 are easy and straightforward issues where sets or dicts don't have any typing.
30 are caused by 2/3 main issues where a method is defined outside of the class file and mypy warns that the method is not recognised on the class. See #1249. It takes quite a bit of effort to get that right, but should be doable even by less experienced `astroid` developers.
20 are caused by attributes being defined as `None` while they should never be `None`. See #1250.
20 are caused by inheritance and design problems that will require some refactoring.

It are especially those last two categories that are difficult to tackle.

**Comment by Pierre-Sassoulas** [comment]
Thanks for the recap !

> We would ignore important issues that might require refactoring. If we then start increasing typing build on incorrect code we can create problems for our future selves.

I'm not advocating for ignoring them ad infinitam, just right now and until we fix them all, so we don't introduce new issue unknowingly because mypy does not check anything unless you launch it yourself :)

Inheritance and design problem in particular sounds like it will take some time to get fixed, so a solution to be able to partially run mypy in the meantime would be beneficial imo.

**Comment by DanielNoord** [comment]
We could write a little script which compares `mypy` output on `main` with the commit in a PR. That might solve that issue in the meantime.

I understand why we would want to disable for now, but the current errors point to actual problems/issues with the current typing. If we disable them people might start adding typing that builds upon these ignored errors. If we then try to resolve these temporary disables, the problem has only become larger. That would only increase the effort to completely type `astroid`. I'd be very hesitant to add ignores for that reason.

**Comment by Pierre-Sassoulas** [comment]
> We could write a little script which compares mypy output on main with the commit in a PR.

This makes sense and shouldn't be too hard to implement (not much more than adding ignores). But how does it prevent that "people might start adding typing that builds upon these ignored errors." ?

**Comment by DanielNoord** [comment]
It doesn't really, but it prevents the issue where the ignore seems to indicate "we acknowledge this is wrong" rather than "we haven't gotten too this yet".

**Comment by DanielNoord** [comment]
In any case, `astroid` development is rather slow so I don't think we'll see much benefit from enabling `mypy` now and going through the effort to add ignores or this trick.

**Comment by Pierre-Sassoulas** [comment]
>  the ignore seems to indicate "we acknowledge this is wrong" rather than "we haven't gotten too this yet".

This argument make a lot of sense, I'm convinced.

**Pull request merged**
