### PR TITLE
Clean-up and fix tox's commands

### LINKED ISSUE #1960: Running `tox` results in `ResolutionImpossible` due to coverage
When trying to run `tox -e py310` in this repo on v2.13.2, I get:

```
Collecting coverage<5
  Using cached coverage-4.5.4.tar.gz (385 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Cannot install coverage<5 and coverage~=7.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested coverage<5
    The user requested coverage~=7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

and indeed, `tox.ini` specifies:

https://github.com/PyCQA/astroid/blob/49691cc04f2d38b174787280f7ed38f818c828bd/tox.ini#L16-L19

but the `requirements_test_min.txt` mentioned there wants:

https://github.com/PyCQA/astroid/blob/49691cc04f2d38b174787280f7ed38f818c828bd/requirements_test_min.txt#L1

It looks like this was pinned over 3 years ago in 128a6ddeddeb817706b3b4a7d5eecb916b9da5d1, and adding it to `requirements_test_min.txt` in 15d2067bcc102e8bdf58d1428d17dcf5b8d6ad28 broke things.

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

This is not working locally because of: ``tox.tox_env.python.virtual_env.package.pyproject.BuildEditableNotSupported`` but I don't know where we're using editable install in the tox script.. .

Closes #1960

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]

**Comment by avylove** [comment]
I tried and it needed to make two changes to get it to work.
- Unpin or bump setuptools in pyproject.toml `build-system.requires`
- Add `allowlist_externals = pre-commit` under `[testenv:formatting]`

**Comment by Pierre-Sassoulas** [comment]
Do you want to take the merge request over @avylove ? If you have a diff I can credit you in this one otherwise :)

**Comment by avylove** [comment]
> Do you want to take the merge request over @avylove ? If you have a diff I can credit you in this one otherwise :)

Either way. I put my changes in https://github.com/avylove/astroid/commits/tox_cleanup. It's based on a rebase of your branch. Not sure if you can change the source branch on this PR to point to it or not.

**Comment by Pierre-Sassoulas** [comment]
Thank you for unblocking this @avylove, I recovered your branch and tested locally, everything works, let's merge !

**Pull request merged**
