### PR TITLE
Parse default values in ``dataclass`` attributes correctly

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Closes https://github.com/PyCQA/pylint/issues/7425

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

My god.. This PR...

Our tests for ``dataclasses`` aren't really good it seems. Oh well, these PRs should help with that as well.

Refs. https://github.com/PyCQA/astroid/pull/1768 https://github.com/PyCQA/astroid/pull/1764 #1770

### CODE REVIEW

**Comment by altendky** [comment]
Passed CI for me again over at https://github.com/Chia-Network/chia-blockchain/runs/8210700017?check_suite_focus=true.  Thanks so much.

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank for the quick fix @DanielNoord, that's amazing. Maybe we need 'crash' primers for astroid, this is getting stressful 😄

**Comment by DanielNoord** [comment]
> Thank for the quick fix @DanielNoord, that's amazing. Maybe we need 'crash' primers for astroid, this is getting stressful 😄

Yeah.. Although I tested against `pylint` and I don't think this failed. The initial PR was fully tested on the `pylint` test suite.

**Comment by Pierre-Sassoulas** [comment]
Do you mean even the pylint primer ? You need to create your own pylint branch in your private repository and launch the test with a modified astroid requirements for this, right ?

**Comment by DanielNoord** [comment]
> Do you mean even the pylint primer ? You need to create your own pylint branch in your private repository and launch the test with a modified astroid requirements for this, right ?

I checked the branch out locally and ran the `pylint` test suite, which worked.

I'm planning on doing the same for every PR automatically in `astroid`, but never got around to implementing it.

We could also start running the primer but that is even more complicated as there are many moving pieces to consider then.

**Comment by Pierre-Sassoulas** [comment]
I did not put a lot of thought into it but maybe we could be using the pylint's primer json and create an astroid ast for each of the project. It might be the right time to extract pylint's testutil to another repository.

**Comment by DanielNoord** [comment]
> I'm doing that too when I'm suspicious of a PR, but it's very manual.

Should be relatively straightforward though in a workflow. Only need to handle crashes which I haven't thought about fully.

> I did not put a lot of thought into it but maybe we could be using the pylint's primer json and create an astroid ast for each of the project. It might be the right time to extract pylint's testutil to another repository.

The main issue is that the whole `primer` package is geared towards running from the `pylint` repo. At some point I want to make a more general package to also be able to use it in `pydocstringformatter`, but so much other stuff to do..

**Comment by Pierre-Sassoulas** [comment]
> At some point I want to make a more general package to also be able to use it in pydocstringformatter

That does sounds great.

>  but so much other stuff to do..

Yeap. Maybe hotfixing astroid will not be one of those stuff anymore when we do 😄 🤞

**Pull request merged**
