### PR TITLE
Add ImportAlias node as children of Import nodes

### PR DESCRIPTION
**Pull request by msuozzo**
## Steps

- [x] For new features or bug fixes, add a ChangeLog entry describing what your PR does.
- [x] Write a good description on what the PR does.

## Description

Since the name and alias metadata was already available as Import.names, the main addition here is of the location metadata associated with the alias. The intent is to generate line- and column-accurate lint locations in pylint for e.g. unused location.

For situations with compound imports (e.g. `from foo import bar, baz, qux`), addressing lints to a specific unused import instead of at the statement granularity as it is now would be a substantial quality-of-life improvement.

The `ImportAlias` node type shadows the `_ast.alias` type in the builtin ast module.

I've left the `Import.names` field to maintain backwards compatibility but it might be nice to change it to type `list(ImportAlias)` in the next major version.

## Type of Changes

|   | Type |
| ------------- | ------------- |
|   | :bug: Bug fix  |
| ✓  | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

### CODE REVIEW

**Comment by msuozzo** [comment]
Any movement here? Should I link to the accompanying pylint change?

**Comment by hippo91** [comment]
@msuozzo thanks for this PR and sorry for the delay. I will try to have a look ASAP.

**Review by hippo91 — CHANGES_REQUESTED** [review]
@msuozzo thanks for this clear development!
Overall it looks good. 
However i think adding tests would gives us more confidence.
Would you mind adding such a test in `unittest_builder.py` or `unittest_raw_building.py`?
By the way i would also have @cdce8p opinion on this.

**Comment by cdce8p** [comment]
I agree, this change should definitely have tests!
As for the code itself, the addition seems reasonable. I don't know what your opinion is @hippo91, but I would prefer to use type annotations for variables (instead of type comments) going forward. Additionally it might be a good idea to define / declare all possible instance variables inside `__init__` and later reassign them, see pylint check for `attribute-defined-outside-init`.

**Comment by cdce8p** [comment]
We will also need to check for unintended side effects with `pylint` before merging it.

**Comment by Pierre-Sassoulas** [comment]
@msuozzo are you still interested in finishing this PR ?

**Comment by DanielNoord** [comment]
Closing this as there no longer seems interest to finish this PR or add tests.

**Pull request closed without merging**
