### PR TITLE
Use constants defined in ``astroid.const`` where applicable

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] Write a good description on what the PR does.

## Description

Something I had on my mind for some time.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I think this is nice change and also a small perf improvement but also that @cdce8p was against it because it makes it harder to detect sys guard. (We reverted some of it before). I don't have strong opinion about this but I also don't want to enter an edit war.

**Comment by DanielNoord** [comment]
I left occurrences for imports and redefinition of methods for specific versions, because of that issue. Of course we could still decide against it. I don't mind leaving as is.

**Comment by Pierre-Sassoulas** [comment]
> I left occurrences for imports and redefinition of methods for specific versions, because of that issue.

Then I think we could merge if Marc do not react before 2.10.

**Comment by cdce8p** [comment]
> > I left occurrences for imports and redefinition of methods for specific versions, because of that issue.
> 
> Then I think we could merge if Marc do not react before 2.10.

Sorry guys! I needed some time to work on different things and just didn't look into any pylint or astroid issues as my backlog was getting larger. Am slowly catching up now, although I probably won't have much free time the next few months. If I'm unresponsive on Github you can usually still reach me on Discord, fyi.

> I think this is nice change and also a small perf improvement but also that @cdce8p was against it because it makes it harder to detect sys guard.

Both mypy and pyright know how to handle `sys` guards. They don't have any logic for arbitrary constant guards. @DanielNoord You mentioned it yourself that you left some sys guards in-place because of it. Thus, I would still recommend against this change.

If performance is that important to you, I would suggest moving the sys guards one level up. E.g. for the `TreeRebuilder` instead of doing the checks inside the individual methods, define the methods itself conditionally. That way the check would only be run once on load, instead of for each method call.

There are some huge drawbacks though. By definition, you'll need to copy a lot of code. With that it will be much more difficult to maintain. That's why I didn't do it when I added the guards for `end_lineno` and `end_col_offset`. IMO it's just not worth it. At some point even Python 3.7 is deprecated and the problem resolves itself.

**Comment by DanielNoord** [comment]
> Sorry guys! I needed some time to work on different things and just didn't look into any pylint or astroid issues as my backlog was getting larger. Am slowly catching up now, although I probably won't have much free time the next few months. If I'm unresponsive on Github you can usually still reach me on Discord, fyi.

As always, no worries! If you have any time to spare on `astroid` or `pylint` issues I think your input would be most valuable on the currently opened `astroid` PRs.  There are both some crucial changes to `distutils` handling as well as the `NamedTuple` instance and mirroring `ast` APIs which would benefit from additional reviews.  

>  At some point even Python 3.7 is deprecated and the problem resolves itself.

Fine with me. I just thought I would propose the change and start the discussion. Let's not do this! Thanks @cdce8p for the input! 😄

**Comment by cdce8p** [comment]
The `distutils` PRs are still on my list. I've also seen a notification about `ast`. I don't want to make any promises, but just maybe I'll get to them.

**Pull request closed without merging**
