### PR TITLE
Conditional test pickle

### PR DESCRIPTION
**Pull request by renefritze**
This is the code as described in #925

### CODE REVIEW

**Review by cdce8p — COMMENTED** [review]
@renefritze Thanks for opening the PR. I'm not sure I fully understand it though. I assume this shouldn't just be a regression test for #925? In that case it would help to also have a test case which is currently failing.

**Comment by renefritze** [comment]
> @renefritze Thanks for opening the PR. I'm not sure I fully understand it though. I assume this shouldn't just be a regression test for #925? In that case it would help to also have a test case which is currently failing.

I've tried to outline this in https://github.com/PyCQA/astroid/issues/925#issue-843129695
If you drop the last commit on my branch here, you get the failure. The idea being that the last commit documents that the issue is somehow related to which function is input into partial. This really isn't meant to be merged at all from my end. I just did as asked to open a PR with the example code.

**Comment by renefritze** [comment]
Can I do anything to make the problem clearer?

**Review by Pierre-Sassoulas — APPROVED** [review]
Sorry for the review time, I was waiting for hippo to review but he's not available right now and this seems pretty safe to merge. Thank you for the merge request :)

**Comment by renefritze** [comment]
Uhm. 

> This really isn't meant to be merged at all from my end. I just did as asked to open a PR with the example code.

**Comment by renefritze** [comment]
I mean, it's safe to merge because it doesn't do anything useful with the last commit included? As I mentioned before, only without the last commit you'll see the potential underlying problem.

**Comment by Pierre-Sassoulas** [comment]
My bad ! If I understand correctly the point of this merge request was to illustrate the problem with pickle ?

**Comment by renefritze** [comment]
> My bad ! If I understand correctly the point of this merge request was to illustrate the problem with pickle ?

Indeed. Maybe I should set the PR branch to the commit with failing tests and add the "fix" just as a comment here? Maybe that would be clearer for everyone?

**Comment by Pierre-Sassoulas** [comment]
:+1: A branch with the latest commit reverted seems like a good idea. (So we can see the error in the CI for each interpreter)

**Comment by renefritze** [comment]
> > My bad ! If I understand correctly the point of this merge request was to illustrate the problem with pickle ?
> 

OK, so just like at the top of #925 I now have two branches again: [supposed to fail](https://github.com/renefritze/astroid/tree/conditional_test_pickle_failing)
 and [supposedly not failing](https://github.com/renefritze/astroid/tree/conditional_test_pickle_no_error)

Then I had to enable GitHub actions for those branches. 
Builds for both branches are now failing everywhere though: https://github.com/renefritze/astroid/actions

IMO the situation as described in #925 with the travis build logs was much clearer :disappointed: 

BTW: don't you want to remove the squashed commit on top in main for this PR?

**Comment by Pierre-Sassoulas** [comment]
Could you open a pull request with the failing branch, please ? It can stay broken as an illustration.

**Pull request merged**
