### PR TITLE
Backport of PR #486

### PR DESCRIPTION
**Pull request by hippo91**
+ Add of ChangeLog entry.

### CODE REVIEW

**Comment by hippo91** [comment]
@PCManticore is there a problem with Travis and python3.x or did i miss something?

**Comment by ceridwen** [comment]
Looks like it's failing because of pylint failures and an unexpected success.  Unfortunately the test output doesn't tell us what the unexpected success *is*.  Can you try running the tests locally to figure out what the unexpected success is?

**Comment by ceridwen** [comment]
Actually, it might be this bug: https://github.com/PyCQA/astroid/issues/472

In which case it's a preexisting issue and nothing to do with your pull request.

**Comment by brycepg** [comment]
We have this issue in master, except I removed the unexpected success. The test is unreliably passing and failing depending on the CI and something else (we think inference tips being overwritten by each other). I think marking this test as ignored is the best option right now.

**Comment by PCManticore** [comment]
@brycepg is right, we can disable the test for now. @hippo91 this is failing the linting, otherwise it is good to go.

**Comment by hippo91** [comment]
Thanks @ceridwen , @brycepg  and @PCManticore .  I replace the decorator @unittest.expectedfailure with @unittest.skip and the CI is ok!.
I merge it.

**Pull request merged**
