### PR TITLE
[codecov] Use our own token to avoid being rate limited

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

See https://github.com/codecov/codecov-action/issues/557\#issuecomment-1224970469

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
At least dependabot / pre-commit (?) and owner MR will work properly. This afternoon the dependabot opened maybe 5 merge request which contributed to the problem. (Also on astroid I do not have a fork, I work directly on the main repo, maybe because I already had contributor right the first time I worked on astroid).

**Comment by DanielNoord** [comment]
Hmm, I have never ran into these issues on `pydocstringformatter` and `pylint` was also fine until today.

Having the coverage broken for any fork PR is really annoying, especially on `pylint`. I would be in favour of waiting with this and seeing if the rate limiting issues were just really high today or if there is a general trend.

**Comment by Pierre-Sassoulas** [comment]
I agree that this is annoying, but this is a (partial) fix why should we wait ?

**Comment by DanielNoord** [comment]
> I agree that this is annoying, but this is a (partial) fix why should we wait ?

Well, it isn't a real fix and breaks our actual workflow. Of the open PRs in both projects less than a quarter a non-fork.
With this change they won't be able to get coverage reports and pass CI.
Re-running manually is annoying, but seems like the better option for now.

**Comment by Pierre-Sassoulas** [comment]
> With this change they won't be able to get coverage reports and pass CI. 

Huh ? Not sure about that. I think this revert to the default of using their (codecov) token ? Look here: https://github.com/PyCQA/pylint/pull/8044 it's a PR from my fork of pylint.

**Review by DanielNoord — APPROVED** [review]
Misinterpreted the comment and the docs. It is only for runs in the forked repository, not in the upstream one!

**Pull request merged**
