### PR TITLE
Upgrade mypy to 0.930

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
http://mypy-lang.blogspot.com/2021/12/mypy-0930-released.html

### CODE REVIEW

**Comment by cdce8p** [comment]
The failure is caused by Python 3.10.1, not the mypy upgrade. Needs to be fixed separately.

**Comment by DanielNoord** [comment]
We postponed updating `tbump` in `pylint` because of that fail, see https://github.com/PyCQA/pylint/issues/5572

**Comment by cdce8p** [comment]
> We postponed updating `tbump` in `pylint` because of that fail, see [PyCQA/pylint#5572](https://github.com/PyCQA/pylint/issues/5572)

@DanielNoord Are you sure those are related? The issue here looks like one with Python 3.10.1 on Windows.
https://github.com/PyCQA/astroid/runs/4618100769?check_suite_focus=true#step:7:70

**Comment by DanielNoord** [comment]
Oh my bad! Didn't read the traceback fully. I saw `distutils` and assumed they were related. Seems like a strange coincidence then.

**Comment by DanielNoord** [comment]
@cdce8p Are you looking into this failure or should somebody else do this? It's affecting tests of other PRs as well so we should probably try and fix this asap.

**Comment by cdce8p** [comment]
> @cdce8p Are you looking into this failure or should somebody else do this? It's affecting tests of other PRs as well so we should probably try and fix this asap.

@DanielNoord I didn't had time for it yet. Do you by chance use Windows? I think that would definitely help when debugging it. I'm on macOS unfortunately for this one.

**Pull request merged**
