### PR TITLE
Fix order of overwritten attributes in inherited dataclasses (#1970)

### PR DESCRIPTION
**Pull request by mbyrnepr2**
Backport of #1970.
FYI @DanielNoord

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Should we release 2.13.3 ?

**Comment by DanielNoord** [comment]
> Should we release 2.13.3 ?

Guess we could? I don't have any immediate PRs in the pipeline!

**Comment by DanielNoord** [comment]
Oh and thanks @mbyrnepr2, much appreciated!

**Comment by mbyrnepr2** [comment]
No worries, anytime!

**Pull request merged**
